on:
  push:
    branches:
      - main  # Set a branch to deploy
      - develop # Note has logic around deployment
      - upgrade-workflows
      
name: build and deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      #GITHUB_PAT: ${{ secrets.GH_OPENPHARMA }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
      - name: Install hugo
        shell: Rscript {0}
        run: |
          blogdown::install_hugo()  

      - name: Build site 
        #if: ${{ github.ref == 'refs/heads/main' }}
        shell: Rscript {0}
        run: |
          blogdown::build_site(build_rmd = TRUE)
          
      - name: Deploy site 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
